run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true

linters:
  disable:
  - exhaustivestruct
  - gci
  - godot
  - nlreturn
  - nolintlint
  - testpackage
  - wrapcheck
  - gomoddirectives
  - ireturn
  - varnamelen
  - paralleltest

linters-settings:
  errcheck:
    exclude-functions:
      - '(github.com/go-kit/log.Logger).Log'
  lll:
    line-length: 200
  funlen:
    lines: 210
    statements: 50
