apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thanos-receive-controller
  namespace: observatorium
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
  - get
