apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: thanos-receive-controller
  name: thanos-receive-controller
  namespace: observatorium
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: thanos-receive-controller
