apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-receive-controller
  namespace: observatorium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-receive-controller
subjects:
- kind: ServiceAccount
  name: thanos-receive-controller
  namespace: observatorium
